#pragma config(Sensor, in2,    ,               sensorAnalog)
#pragma config(Sensor, in3,    ,               sensorAnalog)
#pragma config(Sensor, in4,    backSwitch,     sensorPotentiometer)
#pragma config(Sensor, in5,    ,               sensorAnalog)
#pragma config(Sensor, in7,    frontSwitch,    sensorPotentiometer)
#pragma config(Sensor, dgtl2,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port4,           opMotor,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int power = -127;
int slowPower = -126;
int noPower = 0;
void brake(){
	while(SensorValue[leftEncoder] == 0){
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;
		motor[rightMotor] = noPower;
		motor[leftMotor] = noPower;
	}
}
void firstForward(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[leftEncoder]) <  800){
		motor[rightMotor] = slowPower;
		motor[leftMotor] = power;
		brake();
	}
}
void secondForward(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[rightEncoder]) <  900){
		motor[rightMotor] = slowPower;
		motor[leftMotor] = power;
		brake();
		}
}
void thirdForward(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[rightEncoder]) < 900){
		motor[rightMotor] = slowPower;
		motor[leftMotor] = power;
		brake();
		}
}
void fourthForward(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[rightEncoder]) < 900){
		motor[rightMotor] = slowPower;
		motor[leftMotor] = power;
		brake();
		}
}


void turnLeft(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[rightEncoder]) < 300){
		motor[rightMotor] = -power;
		motor[leftMotor] = power;
	}
}
void turnRight(){
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(abs(SensorValue[leftEncoder]) < 150){
		motor[rightMotor] = power;
		motor[leftMotor] = -power;
	}
}
void automaticStraighten(){}
void automaticStraight(){
	while(abs(SensorValue[leftEncoder]) < 1260)
	{
		if(SensorValue[leftEncoder] > SensorValue[rightMotor])
		{
			motor[rightMotor] = power;
			motor[leftMotor] = slowPower;
		}
		if(SensorValue[rightEncoder] > SensorValue[leftEncoder])
		{
			motor[rightMotor] = slowPower;
			motor[leftMotor] = power;
		}
		if(SensorValue[leftEncoder] == SensorValue[rightEncoder])
		{
			motor[rightMotor] = power;
			motor[leftMotor] = power;
		}
	}
}

task main(){
	automaticStraighten();
	wait1Msec(3000);
	firstForward();
	turnLeft();
	secondForward();
	turnRight();
	thirdForward();
	turnRight();
	fourthForward();
}
