#pragma config(Motor,  port1,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightMotor] = 96;
motor[leftMotor] = -96;
wait1Msec(500);
}
