#pragma config(Sensor, in1,    lightSensor,    sensorReflection)
#pragma config(Sensor, in2,    rightLine,      sensorLineFollower)
#pragma config(Sensor, in3,    middleLine,     sensorLineFollower)
#pragma config(Sensor, in4,    leftLine,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl2,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 2000;
int speed = 55;
int turnSpeed = 100;
int slow = 20;
int backspeed= -speed;
int backslow = -slow;

void followLine ()
{
	while(true){
		if (SensorValue[sonarSensor]>15 || SensorValue[sonarSensor]<0){
		// If there is nothing in front, this runs

			if(SensorValue(rightLine) > threshold)
			{
				motor[leftMotor] = turnSpeed;
				motor[rightMotor] = -30;
			}

			if(SensorValue(middleLine) > threshold)
			{
				motor[leftMotor] = speed;
				motor[rightMotor] = speed;
			}

			if(SensorValue(leftLine) > threshold)
			{
				motor[leftMotor] = -30;
				motor[rightMotor] = turnSpeed;
			}
		}
		else {
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
	}
}
task main()
{
	wait1Msec(3000);
	followLine();
}
