#pragma config(Sensor, dgtl9,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           armMotor,      tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

// Left Joystick controlls higher power robtot drive train
while(true){
		motor[leftMotor] = vexRT[Ch3] + vexRT[Ch2] / 3;
		motor[rightMotor] = vexRT[Ch3] + vexRT[Ch2] / 3;
		//if(vexRT[Ch4] > 0){
			motor[leftMotor] = vexRT[Ch4];
			motor[rightMotor] = -vexRT[Ch4];
	//} //else if(vexRT[Ch4] < 0){
			//motor[leftMotor] = -vexRT[Ch4];
			//motor[rightMotor] = vexRT[Ch4];
		//}
		//else{}
	}
}
