#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  killSwitch,     sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// Autonomous
	while(vexRT[Btn7D] == 0)

	// Has to press killSwitch to start
	{while(SensorValue[killSwitch] == 1){

		}
	}

	ClearTimer(T1);


	while(time1[T1] < 90000){
		// Jog Left --Fast!
		while(vexRT[Btn8R] == 1){
			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;

	while(SensorValue[rightEncoder] > -10){
				motor[rightMotor] = 127;
				motor[leftMotor] = -127;
			}
		}
		// Jog Right --Fast!
		while(vexRT[Btn8L] == 1){
			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;
			while(SensorValue[leftEncoder] > -10){
				motor[rightMotor] = -127;
				motor[leftMotor] = 127;
			}
		}
		// Jog Left --Slow!
		while(vexRT[Btn7R] == 1){
			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;

			while(SensorValue[rightEncoder] > -5){
				motor[rightMotor] = 63;
				motor[leftMotor] = -63;
			}
		}
		// Jog Right --Slow!
		while(vexRT[Btn7L] == 1){
			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;
			while(SensorValue[leftEncoder] > -5){
				motor[rightMotor] = -63;
				motor[leftMotor] = 63;
			}
		}
		motor[leftMotor] = -vexRT[Ch3];
		motor[rightMotor] = -vexRT[Ch3];

		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 127;
		}
		else
		{
			motor[armMotor] = 0;
		}
		if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -127;
		}
		else
		{
			motor[armMotor] = 0;
		}
	}

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[armMotor] = 0;


	//get(lefthandedAllenWrenches);
	//get(pneumaticwiring);
	//promote[KnoxCrichton]to(SafetyDaddy);
	//setteamname(3824_the_Rohotics);
	//get(OG4Rotors40kpa);
	//get(deleteTyler_);
	//getBetterAllianceMemberatSMR(3140);
	//get(notShaftedAtWorlds) > (regionalChairmans);
	//get(betterAtChairman's);
	//order(prostitutes);
	//upgrade(robotdriver) to --version "Caleb";
	//get(racialDiversity);
	//get(eintiensDub);
	//get(clapNation);
  //get(betterCode);

}
