#pragma config(ProgramType, StandaloneWiFi)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor, port2, rightMotor, tmotorNormal, openLoop, reversed)
#pragma config(Motor, port3, leftMotor, tmotorNormal, openLoop)
#pragma config(Motor, port6, armMotor, tmotorNormal, openLoop)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(vexRT[Btn7D] == 0)
	{
	}

	ClearTimer(T1);

	while(time1[T1] < 900000)
	{
		while(vexRT[Btn8L] == 1){
			SensorValue[rightEncoder] = 0;
			SensorValue[leftEncoder] = 0;

			while(SensorValue[rightEncoder] < 18){
				motor[rightMotor] = 127;
				motor[leftMotor] = -127;
			}
	}
		motor[leftMotor] = vexRT[Ch3] / 2;
		motor[rightMotor] = vexRT[Ch3] / 2;

		if(vexRT[Btn6U] == 1)
		{
			motor[armMotor] = 127;
		}
		else
		{
			motor[armMotor] = 0;
		}
		if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -127;
		}
		else
		{
			motor[armMotor] = 0;
		}
	}

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	motor[armMotor] = 0;

}
