#pragma config(Motor,  port1,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Code by Alex Bingham, Knox Crichton, Moriah Brown
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


// Sad function that makes the robot stop
void brake(){
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
	wait1Msec(600);
}

// Function that's like forward, but OP though
void midForward(){\
	brake();
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
	wait1Msec(1200);
}

// Function to simplify forward movement to single command, will drive forward for 3 seconds
void driveForward(){
	brake();
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
	wait1Msec(710);
}

// Lighter drive time for finishing straight
void slowForward(){
	brake();
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
	wait1Msec(350);
}

// Like slow forward but even worse
void finishForward(){
	brake();
	motor[leftMotor] = 127;
	motor[rightMotor] = 127;
	wait1Msec(250);
	brake();
}
// Function to simplify left turns, will spin left for a breif time
void turnLeft(){
	brake();
	motor[leftMotor] = -127;
	motor[rightMotor] = 127;
	wait1Msec(240);
}

// Function to simplify right turns, will spin right for a breif time
void turnRight(){
	brake();
	motor[leftMotor] = 127;
	motor[rightMotor] = -127;
	wait1Msec(365);
}

// Function that turns right, but its not OP
void turnRightXD(){
	brake();
	motor[leftMotor] = 127;
	motor[rightMotor] = -127;
	wait1Msec(285);
}


task main()
{
	wait1Msec(3000);
	driveForward();
	turnLeft();
	driveForward();
	turnRight();
	slowForward();
	turnRightXD();
	finishForward();
}
