// Code by Alex Bingham, Knox Crichton, Moriah Brown
#pragma config(Motor,  port2,           leftMotor,     tmotorVex269, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Function to simplify forward movement to single command, will drive forward for 3 seconds
void driveForward(){
	motor[rightMotor] = 127;
	motor[leftMotor] = 127;
	wait1Msec(3000);
}

// Function to simplify left turns, will spin left for half a second.
void turnLeft(){
	motor[leftMotor] = 127;
	motor[rightMotor] = -127;
	wait1Msec(500);
}

// Function to simplify right turns, will spin right for half a second
void turnRight(){
	motor[leftMotor] = -127;
	motor[rightMotor] = 127;
	wait1Msec(500);
}


task main()
{
driveForward();
turnLeft();
driveForward();
turnRight();
driveForward();
turnRight();
}
