#pragma config(Motor,  port1,           rightMotor,    tmotorVex269, openLoop)
#pragma config(Motor,  port10,          leftMotor,     tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Code by Alex Bingham, Knox Crichton, Moriah Brown
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Function to simplify forward movement to single command, will drive forward for 3 seconds
void driveForward(){
	motor[leftMotor] = 170;
	motor[rightMotor] = 170;
	wait1Msec(3000);
}

// Function to simplify left turns, will spin left for half a second.
void turnLeft(){
	motor[leftMotor] = 170;
	motor[rightMotor] = -170;
	wait1Msec(500);
}

// Function to simplify right turns, will spin right for half a second
void turnRight(){
	motor[leftMotor] = -170;
	motor[rightMotor] = 170;
	wait1Msec(500);
}


task main()
{
wait1Msec(10000);
driveForward();
turnLeft();
driveForward();
turnRight();
driveForward();
turnRight();
}
